spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        default_schema: ${DATABASE_SCHEMA:financial-balancing}
  datasource:
    username: ${DATABASE_USER:financial}
    password: ${DATABASE_PASS:financial}
    jdbcUrl: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:santosystem}?currentSchema=${DATABASE_SCHEMA:financial_balancing}
    driver-class-name: org.postgresql.Driver
  flyway:
    color: always

server:
  port: ${HTTP_PORT:8081}
  servlet:
    context-path: /${APP_NAME:financial-balancing}

# swagger-ui custom path
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  packagesToScan: com.santosystem.financial.balancing
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui

logbook:
  exclude:
    - /actuator/**
    - /health
    - /api/admin/**
    - /admin/**
  format.style: json
