package com.santosystem.financial.balancing.model.enums

enum class SubSector(val value: String) {
    PETROLEO_GAS_E_BIOCOMBUSTIVEIS("PETRÓLEO, GÁS E BIOCOMBUSTÍVEIS"),
    MINERACAO("MINERAÇÃO"),
    SIDERURGIA_E_METALURGIA("SIDERURGIA E METALURGIA"),
    QUIMICOS("QUÍMICOS"),
    MADEIRA_E_PAPEL("MADEIRA E PAPEL"),
    EMBALAGENS("EMBALAGENS"),
    MATERIAIS_DIVERSOS("MATERIAIS DIVERSOS"),
    CONSTRUCAO_E_ENGENHARIA("CONSTRUÇÃO E ENGENHARIA"),
    MATERIAL_DE_TRANSPORTE("MATERIAL DE TRANSPORTE"),
    MAQUINAS_E_EQUIPAMENTOS("MÁQUINAS E EQUIPAMENTOS"),
    TRANSPORTE("TRANSPORTE"),
    SERVICOS_DIVERSOS("SERVIÇOS DIVERSOS"),
    COMERCIO("COMÉRCIO"),
    AGROPECUARIA("AGROPECUÁRIA"),
    ALIMENTOS_PROCESSADOS("ALIMENTOS PROCESSADOS"),
    BEBIDAS("BEBIDAS"),
    PRODUTOS_DE_USO_PESSOAL_E_DE_LIMPEZA("PRODUTOS DE USO PESSOAL E DE LIMPEZA"),
    COMERCIO_E_DISTRIBUICAO("COMÉRCIO E DISTRIBUIÇÃO"),
    CONSTRUCAO_CIVIL("CONSTRUÇÃO CIVIL"),
    TECIDOS_VESTUARIO_E_CALCADOS("TECIDOS, VESTUÁRIO E CALÇADOS"),
    UTILIDADES_DOMESTICAS("UTILIDADES DOMÉSTICAS"),
    AUTOMOVEIS_E_MOTOCICLETAS("AUTOMÓVEIS E MOTOCICLETAS"),
    HOTEIS_E_RESTAURANTES("HOTEIS E RESTAURANTES"),
    VIAGENS_E_LAZER("VIAGENS E LAZER"),
    DIVERSOS("DIVERSOS"),
    MEDICAMENTOS_E_OUTROS_PRODUTOS("MEDICAMENTOS E OUTROS PRODUTOS"),
    SERVICOS_MEDICO_HOSPITALARES_ANALISES_E_DIAGNOSTICOS("SERVIÇOS MÉDICO - HOSPITALARES, ANÁLISES E DIAGNÓSTICOS"),
    EQUIPAMENTOS("EQUIPAMENTOS"),
    COMPUTADORES_E_EQUIPAMENTOS("COMPUTADORES E EQUIPAMENTOS"),
    PROGRAMAS_E_SERVICOS("PROGRAMAS E SERVIÇOS"),
    TELECOMUNICACOES("TELECOMUNICAÇÕES"),
    MIDIA("MÍDIA"),
    ENERGIA_ELETRICA("ENERGIA ELÉTRICA"),
    AGUA_E_SANEAMENTO("ÁGUA E SANEAMENTO"),
    GAS("GÁS"),
    INTERMEDIARIOS_FINANCEIROS("INTERMEDIÁRIOS FINANCEIROS"),
    SECURITIZADORAS_DE_RECEBIVEIS("SECURITIZADORAS DE RECEBÍVEIS"),
    SERVICOS_FINANCEIROS_DIVERSOS("SERVIÇOS FINANCEIROS DIVERSOS"),
    PREVIDENCIA_E_SEGUROS("PREVIDÊNCIA E SEGUROS"),
    EXPLORACAO_DE_IMOVEIS("EXPLORAÇÃO DE IMÓVEIS"),
    HOLDINGS_DIVERSIFICADAS("HOLDINGS DIVERSIFICADAS"),
    OUTROS_TITULOS("OUTROS TÍTULOS"),
    OUTROS("OUTROS"),
    SERVICOS("SERVIÇOS"),
    UNDEFINED("NÃO DEFINIDO");

    companion object {
        fun getSubSector(value: String) = try {
            valueOf(value.uppercase())
        } catch (ex: IllegalArgumentException) {
            UNDEFINED
        }
    }

}
